# Generated by Django 4.2.3 on 2023-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Комментарий')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='file-name', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('file_type', models.TextField(default='jpg')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_text', models.TextField(default='Текст объявления')),
                ('category', models.CharField(choices=[('TK', 'Танки'), ('HL', 'Хилеры'), ('DD', 'ДД'), ('TD', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('LD', 'Кожевники'), ('PN', 'Зельевары'), ('MS', 'Мастера заклинаний')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
